import { pino, type DestinationStream, type Level, type Logger as PinoLogger } from 'pino';
import { contextFields } from './context.js';
import { sanitizeRecord, scrubString, type LogMode, type SanitizeOptions } from './redaction.js';

export interface LoggerOptions {
  /** Service name, added to every line. */
  service: string;
  level?: Level;
  /**
   * `redact` (default): any field is allowed but sensitive keys and values are masked.
   * `allowlist`: only `allowedFields` and the safe base fields are written. Use for restricted services.
   */
  mode?: LogMode;
  allowedFields?: readonly string[];
  extraRedactKeys?: readonly string[];
  /** Where lines go. Defaults to stdout. */
  destination?: DestinationStream;
}

type Fields = Record<string, unknown>;

export interface Logger {
  trace(fields: Fields | Error, msg?: string): void;
  trace(msg: string): void;
  debug(fields: Fields | Error, msg?: string): void;
  debug(msg: string): void;
  info(fields: Fields | Error, msg?: string): void;
  info(msg: string): void;
  warn(fields: Fields | Error, msg?: string): void;
  warn(msg: string): void;
  error(fields: Fields | Error, msg?: string): void;
  error(msg: string): void;
  fatal(fields: Fields | Error, msg?: string): void;
  fatal(msg: string): void;
  /** Child logger. Bindings pass through the same sanitiser. */
  child(bindings: Fields): Logger;
}

const LEVELS = ['trace', 'debug', 'info', 'warn', 'error', 'fatal'] as const;

function wrap(base: PinoLogger, options: SanitizeOptions): Logger {
  const write = (level: Level) => (first: unknown, second?: unknown) => {
    // No printf-style interpolation: extra arguments are never formatted into the message.
    const fields = typeof first === 'string' ? {} : sanitizeRecord(first, options);
    const rawMsg = typeof first === 'string' ? first : second;
    const msg = typeof rawMsg === 'string' ? scrubString(rawMsg) : undefined;
    if (msg === undefined) base[level](fields);
    else base[level](fields, '%s', msg);
  };

  const logger = {} as Record<string, unknown>;
  for (const level of LEVELS) logger[level] = write(level);
  logger['child'] = (bindings: Fields) =>
    wrap(base.child(sanitizeRecord(bindings, options)), options);
  return logger as unknown as Logger;
}

/**
 * Creates the only logger service code may use. Output is JSON, one object per line.
 * Redaction cannot be turned off; callers can only make it stricter.
 */
export function createLogger(options: LoggerOptions): Logger {
  const mode = options.mode ?? 'redact';
  const sanitizeOptions: SanitizeOptions = {
    mode,
    ...(options.extraRedactKeys ? { extraRedactKeys: options.extraRedactKeys } : {}),
    ...(options.allowedFields ? { allowedFields: options.allowedFields } : {}),
  };

  const base = pino(
    {
      level: options.level ?? 'info',
      base: { service: options.service },
      timestamp: pino.stdTimeFunctions.isoTime,
      messageKey: 'msg',
      // request id, trace id and span id are generated by us, never taken from caller data
      mixin: contextFields,
      formatters: {
        level: (label) => ({ level: label }),
        // Defence in depth: anything that reaches pino directly is sanitised too.
        log: (object) => sanitizeRecord(object, sanitizeOptions),
      },
    },
    options.destination,
  );

  return wrap(base, sanitizeOptions);
}
